<?php

/**
 * BaseSpecialty
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property Doctrine_Collection $Questions
 * @property Doctrine_Collection $Specialist
 * @property Doctrine_Collection $Prompt
 * @property Doctrine_Collection $QuestionSpecialty
 * @property Doctrine_Collection $SheetHistory
 * @property Doctrine_Collection $SheetHistorySpecialty
 * 
 * @method string              getTitle()                 Returns the current record's "title" value
 * @method string              getDescription()           Returns the current record's "description" value
 * @method Doctrine_Collection getQuestions()             Returns the current record's "Questions" collection
 * @method Doctrine_Collection getSpecialist()            Returns the current record's "Specialist" collection
 * @method Doctrine_Collection getPrompt()                Returns the current record's "Prompt" collection
 * @method Doctrine_Collection getQuestionSpecialty()     Returns the current record's "QuestionSpecialty" collection
 * @method Doctrine_Collection getSheetHistory()          Returns the current record's "SheetHistory" collection
 * @method Doctrine_Collection getSheetHistorySpecialty() Returns the current record's "SheetHistorySpecialty" collection
 * @method Specialty           setTitle()                 Sets the current record's "title" value
 * @method Specialty           setDescription()           Sets the current record's "description" value
 * @method Specialty           setQuestions()             Sets the current record's "Questions" collection
 * @method Specialty           setSpecialist()            Sets the current record's "Specialist" collection
 * @method Specialty           setPrompt()                Sets the current record's "Prompt" collection
 * @method Specialty           setQuestionSpecialty()     Sets the current record's "QuestionSpecialty" collection
 * @method Specialty           setSheetHistory()          Sets the current record's "SheetHistory" collection
 * @method Specialty           setSheetHistorySpecialty() Sets the current record's "SheetHistorySpecialty" collection
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSpecialty extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('specialty');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Question as Questions', array(
             'refClass' => 'QuestionSpecialty',
             'local' => 'specialty_id',
             'foreign' => 'question_id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Specialist', array(
             'local' => 'id',
             'foreign' => 'specialty_id'));

        $this->hasMany('Prompt', array(
             'local' => 'id',
             'foreign' => 'specialty_id'));

        $this->hasMany('QuestionSpecialty', array(
             'local' => 'id',
             'foreign' => 'specialty_id'));

        $this->hasMany('SheetHistory', array(
             'refClass' => 'SheetHistorySpecialty',
             'local' => 'specialty_id',
             'foreign' => 'sheet_history_id'));

        $this->hasMany('SheetHistorySpecialty', array(
             'local' => 'id',
             'foreign' => 'specialty_id'));
    }
}