<?php

/**
 * BaseAnalysis
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $answer_id
 * @property integer $user_id
 * @property integer $analysis_type_id
 * @property string $photo
 * @property Answer $Answer
 * @property User $User
 * @property Analysis_type $Analysis_type
 * 
 * @method integer       getAnswerId()         Returns the current record's "answer_id" value
 * @method integer       getUserId()           Returns the current record's "user_id" value
 * @method integer       getAnalysisTypeId()   Returns the current record's "analysis_type_id" value
 * @method string        getPhoto()            Returns the current record's "photo" value
 * @method Answer        getAnswer()           Returns the current record's "Answer" value
 * @method User          getUser()             Returns the current record's "User" value
 * @method Analysis_type getAnalysisType()     Returns the current record's "Analysis_type" value
 * @method Analysis      setAnswerId()         Sets the current record's "answer_id" value
 * @method Analysis      setUserId()           Sets the current record's "user_id" value
 * @method Analysis      setAnalysisTypeId()   Sets the current record's "analysis_type_id" value
 * @method Analysis      setPhoto()            Sets the current record's "photo" value
 * @method Analysis      setAnswer()           Sets the current record's "Answer" value
 * @method Analysis      setUser()             Sets the current record's "User" value
 * @method Analysis      setAnalysisType()     Sets the current record's "Analysis_type" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnalysis extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('analysis');
        $this->hasColumn('answer_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('analysis_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('photo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Answer', array(
             'local' => 'answer_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Analysis_type', array(
             'local' => 'analysis_type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}