<?php

/**
 * BaseArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $specialist_id
 * @property text $title
 * @property string $title_url
 * @property string $photo
 * @property string $video
 * @property string $description
 * @property text $body
 * @property boolean $is_activated
 * @property Specialist $Specialist
 * @property Doctrine_Collection $Comment
 * 
 * @method integer             getSpecialistId()  Returns the current record's "specialist_id" value
 * @method text                getTitle()         Returns the current record's "title" value
 * @method string              getTitleUrl()      Returns the current record's "title_url" value
 * @method string              getPhoto()         Returns the current record's "photo" value
 * @method string              getVideo()         Returns the current record's "video" value
 * @method string              getDescription()   Returns the current record's "description" value
 * @method text                getBody()          Returns the current record's "body" value
 * @method boolean             getIsActivated()   Returns the current record's "is_activated" value
 * @method Specialist          getSpecialist()    Returns the current record's "Specialist" value
 * @method Doctrine_Collection getComment()       Returns the current record's "Comment" collection
 * @method Article             setSpecialistId()  Sets the current record's "specialist_id" value
 * @method Article             setTitle()         Sets the current record's "title" value
 * @method Article             setTitleUrl()      Sets the current record's "title_url" value
 * @method Article             setPhoto()         Sets the current record's "photo" value
 * @method Article             setVideo()         Sets the current record's "video" value
 * @method Article             setDescription()   Sets the current record's "description" value
 * @method Article             setBody()          Sets the current record's "body" value
 * @method Article             setIsActivated()   Sets the current record's "is_activated" value
 * @method Article             setSpecialist()    Sets the current record's "Specialist" value
 * @method Article             setComment()       Sets the current record's "Comment" collection
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article');
        $this->hasColumn('specialist_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('title_url', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
        $this->hasColumn('photo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('video', 'string', 1000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 1000,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('body', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Specialist', array(
             'local' => 'specialist_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Comment', array(
             'local' => 'id',
             'foreign' => 'article_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}