<?php

/**
 * BaseQuestionSheetHistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $question_id
 * @property integer $sheet_history_field_id
 * @property string $value
 * @property Question $Question
 * @property SheetHistoryField $SheetHistoryField
 * 
 * @method integer              getQuestionId()             Returns the current record's "question_id" value
 * @method integer              getSheetHistoryFieldId()    Returns the current record's "sheet_history_field_id" value
 * @method string               getValue()                  Returns the current record's "value" value
 * @method Question             getQuestion()               Returns the current record's "Question" value
 * @method SheetHistoryField    getSheetHistoryField()      Returns the current record's "SheetHistoryField" value
 * @method QuestionSheetHistory setQuestionId()             Sets the current record's "question_id" value
 * @method QuestionSheetHistory setSheetHistoryFieldId()    Sets the current record's "sheet_history_field_id" value
 * @method QuestionSheetHistory setValue()                  Sets the current record's "value" value
 * @method QuestionSheetHistory setQuestion()               Sets the current record's "Question" value
 * @method QuestionSheetHistory setSheetHistoryField()      Sets the current record's "SheetHistoryField" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuestionSheetHistory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('question_sheet_history');
        $this->hasColumn('question_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('sheet_history_field_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('value', 'string', 100000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Question', array(
             'local' => 'question_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('SheetHistoryField', array(
             'local' => 'sheet_history_field_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}