<?php

/**
 * BaseComplaint
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $question_id
 * @property integer $specialist_id
 * @property text $body
 * @property Question $Question
 * @property Specialist $Specialist
 * 
 * @method integer    getQuestionId()    Returns the current record's "question_id" value
 * @method integer    getSpecialistId()  Returns the current record's "specialist_id" value
 * @method text       getBody()          Returns the current record's "body" value
 * @method Question   getQuestion()      Returns the current record's "Question" value
 * @method Specialist getSpecialist()    Returns the current record's "Specialist" value
 * @method Complaint  setQuestionId()    Sets the current record's "question_id" value
 * @method Complaint  setSpecialistId()  Sets the current record's "specialist_id" value
 * @method Complaint  setBody()          Sets the current record's "body" value
 * @method Complaint  setQuestion()      Sets the current record's "Question" value
 * @method Complaint  setSpecialist()    Sets the current record's "Specialist" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComplaint extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('complaint');
        $this->hasColumn('question_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('specialist_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('body', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Question', array(
             'local' => 'question_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Specialist', array(
             'local' => 'specialist_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}