<?php

/**
 * BaseNews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $title_url
 * @property text $body
 * @property string $photo
 * @property string $video
 * 
 * @method string getTitle()     Returns the current record's "title" value
 * @method string getTitleUrl()  Returns the current record's "title_url" value
 * @method text   getBody()      Returns the current record's "body" value
 * @method string getPhoto()     Returns the current record's "photo" value
 * @method string getVideo()     Returns the current record's "video" value
 * @method News   setTitle()     Sets the current record's "title" value
 * @method News   setTitleUrl()  Sets the current record's "title_url" value
 * @method News   setBody()      Sets the current record's "body" value
 * @method News   setPhoto()     Sets the current record's "photo" value
 * @method News   setVideo()     Sets the current record's "video" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('news');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('title_url', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
        $this->hasColumn('body', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('photo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('video', 'string', 1000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}