<?php

/**
 * BaseSeo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title_h
 * @property string $title_tag
 * @property string $description_tag
 * @property string $url
 * 
 * @method string getTitleH()          Returns the current record's "title_h" value
 * @method string getTitleTag()        Returns the current record's "title_tag" value
 * @method string getDescriptionTag()  Returns the current record's "description_tag" value
 * @method string getUrl()             Returns the current record's "url" value
 * @method Seo    setTitleH()          Sets the current record's "title_h" value
 * @method Seo    setTitleTag()        Sets the current record's "title_tag" value
 * @method Seo    setDescriptionTag()  Sets the current record's "description_tag" value
 * @method Seo    setUrl()             Sets the current record's "url" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSeo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seo');
        $this->hasColumn('title_h', 'string', 1000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 1000,
             ));
        $this->hasColumn('title_tag', 'string', 1000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 1000,
             ));
        $this->hasColumn('description_tag', 'string', 1000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 1000,
             ));
        $this->hasColumn('url', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}