<?php

/**
 * BaseConsilium_answer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $consilium_id
 * @property integer $specialist_id
 * @property text $body
 * @property Consilium $Consilium
 * @property Specialist $Specialist
 * 
 * @method integer          getConsiliumId()   Returns the current record's "consilium_id" value
 * @method integer          getSpecialistId()  Returns the current record's "specialist_id" value
 * @method text             getBody()          Returns the current record's "body" value
 * @method Consilium        getConsilium()     Returns the current record's "Consilium" value
 * @method Specialist       getSpecialist()    Returns the current record's "Specialist" value
 * @method Consilium_answer setConsiliumId()   Sets the current record's "consilium_id" value
 * @method Consilium_answer setSpecialistId()  Sets the current record's "specialist_id" value
 * @method Consilium_answer setBody()          Sets the current record's "body" value
 * @method Consilium_answer setConsilium()     Sets the current record's "Consilium" value
 * @method Consilium_answer setSpecialist()    Sets the current record's "Specialist" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConsilium_answer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('consilium_answer');
        $this->hasColumn('consilium_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('specialist_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('body', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Consilium', array(
             'local' => 'consilium_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Specialist', array(
             'local' => 'specialist_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}