<?php

/**
 * BaseAnalysis_type
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property Doctrine_Collection $Analysis
 * 
 * @method string              getTitle()       Returns the current record's "title" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getAnalysis()    Returns the current record's "Analysis" collection
 * @method Analysis_type       setTitle()       Sets the current record's "title" value
 * @method Analysis_type       setDescription() Sets the current record's "description" value
 * @method Analysis_type       setAnalysis()    Sets the current record's "Analysis" collection
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnalysis_type extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('analysis_type');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Analysis', array(
             'local' => 'id',
             'foreign' => 'analysis_type_id'));
    }
}