<?php

/**
 * BaseAgreement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property string $body
 * @property string $file
 * @property boolean $in_documentation
 * @property Doctrine_Collection $AgreementComplete
 * 
 * @method string              getTitle()             Returns the current record's "title" value
 * @method string              getDescription()       Returns the current record's "description" value
 * @method string              getBody()              Returns the current record's "body" value
 * @method string              getFile()              Returns the current record's "file" value
 * @method boolean             getInDocumentation()   Returns the current record's "in_documentation" value
 * @method Doctrine_Collection getAgreementComplete() Returns the current record's "AgreementComplete" collection
 * @method Agreement           setTitle()             Sets the current record's "title" value
 * @method Agreement           setDescription()       Sets the current record's "description" value
 * @method Agreement           setBody()              Sets the current record's "body" value
 * @method Agreement           setFile()              Sets the current record's "file" value
 * @method Agreement           setInDocumentation()   Sets the current record's "in_documentation" value
 * @method Agreement           setAgreementComplete() Sets the current record's "AgreementComplete" collection
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAgreement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('agreement');
        $this->hasColumn('title', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
        $this->hasColumn('body', 'string', 10000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 10000,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('in_documentation', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AgreementComplete', array(
             'local' => 'id',
             'foreign' => 'agreement_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}