<?php

/**
 * BaseSheetHistorySpecialty
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sheet_history_id
 * @property integer $specialty_id
 * @property SheetHistory $SheetHistory
 * @property Specialty $Specialty
 * 
 * @method integer               getSheetHistoryId()   Returns the current record's "sheet_history_id" value
 * @method integer               getSpecialtyId()      Returns the current record's "specialty_id" value
 * @method SheetHistory          getSheetHistory()     Returns the current record's "SheetHistory" value
 * @method Specialty             getSpecialty()        Returns the current record's "Specialty" value
 * @method SheetHistorySpecialty setSheetHistoryId()   Sets the current record's "sheet_history_id" value
 * @method SheetHistorySpecialty setSpecialtyId()      Sets the current record's "specialty_id" value
 * @method SheetHistorySpecialty setSheetHistory()     Sets the current record's "SheetHistory" value
 * @method SheetHistorySpecialty setSpecialty()        Sets the current record's "Specialty" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSheetHistorySpecialty extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sheet_history_specialty');
        $this->hasColumn('sheet_history_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('specialty_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SheetHistory', array(
             'local' => 'sheet_history_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Specialty', array(
             'local' => 'specialty_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}