<?php

/**
 * BaseUserGroupUsers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $user_group_id
 * 
 * @method integer        getUserId()        Returns the current record's "user_id" value
 * @method integer        getUserGroupId()   Returns the current record's "user_group_id" value
 * @method UserGroupUsers setUserId()        Sets the current record's "user_id" value
 * @method UserGroupUsers setUserGroupId()   Sets the current record's "user_group_id" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserGroupUsers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_group_users');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('user_group_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}