<?php

/**
 * BaseAttached_family_users
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $user_about_id
 * @property User $User
 * @property User $UserAbout
 * 
 * @method integer               getUserId()        Returns the current record's "user_id" value
 * @method integer               getUserAboutId()   Returns the current record's "user_about_id" value
 * @method User                  getUser()          Returns the current record's "User" value
 * @method User                  getUserAbout()     Returns the current record's "UserAbout" value
 * @method Attached_family_users setUserId()        Sets the current record's "user_id" value
 * @method Attached_family_users setUserAboutId()   Sets the current record's "user_about_id" value
 * @method Attached_family_users setUser()          Sets the current record's "User" value
 * @method Attached_family_users setUserAbout()     Sets the current record's "UserAbout" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAttached_family_users extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('attached_family_users');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_about_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('User as UserAbout', array(
             'local' => 'user_about_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}