<?php

/**
 * BaseSpecialist_work_place
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $specialist_id
 * @property string $title
 * @property boolean $hidden
 * @property Specialist $Specialist
 * @property Doctrine_Collection $Reception_contract
 * @property Doctrine_Collection $ReceiveLocation
 * 
 * @method integer               getSpecialistId()       Returns the current record's "specialist_id" value
 * @method string                getTitle()              Returns the current record's "title" value
 * @method boolean               getHidden()             Returns the current record's "hidden" value
 * @method Specialist            getSpecialist()         Returns the current record's "Specialist" value
 * @method Doctrine_Collection   getReceptionContract()  Returns the current record's "Reception_contract" collection
 * @method Doctrine_Collection   getReceiveLocation()    Returns the current record's "ReceiveLocation" collection
 * @method Specialist_work_place setSpecialistId()       Sets the current record's "specialist_id" value
 * @method Specialist_work_place setTitle()              Sets the current record's "title" value
 * @method Specialist_work_place setHidden()             Sets the current record's "hidden" value
 * @method Specialist_work_place setSpecialist()         Sets the current record's "Specialist" value
 * @method Specialist_work_place setReceptionContract()  Sets the current record's "Reception_contract" collection
 * @method Specialist_work_place setReceiveLocation()    Sets the current record's "ReceiveLocation" collection
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSpecialist_work_place extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('specialist_work_place');
        $this->hasColumn('specialist_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('hidden', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Specialist', array(
             'local' => 'specialist_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Reception_contract', array(
             'refClass' => 'ReceiveLocation',
             'local' => 'work_place_id',
             'foreign' => 'reception_id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ReceiveLocation', array(
             'local' => 'id',
             'foreign' => 'work_place_id'));
    }
}