<?php

/**
 * BaseQuestionData
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $question_id
 * @property Question $Question
 * 
 * @method integer      getQuestionId()  Returns the current record's "question_id" value
 * @method Question     getQuestion()    Returns the current record's "Question" value
 * @method QuestionData setQuestionId()  Sets the current record's "question_id" value
 * @method QuestionData setQuestion()    Sets the current record's "Question" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuestionData extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('question_data');
        $this->hasColumn('question_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Question', array(
             'local' => 'question_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}