<?php

/**
 * BaseLpuSpecialist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $lpu_id
 * @property integer $specialist_id
 * 
 * @method integer       getLpuId()         Returns the current record's "lpu_id" value
 * @method integer       getSpecialistId()  Returns the current record's "specialist_id" value
 * @method LpuSpecialist setLpuId()         Sets the current record's "lpu_id" value
 * @method LpuSpecialist setSpecialistId()  Sets the current record's "specialist_id" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLpuSpecialist extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lpu_specialist');
        $this->hasColumn('lpu_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('specialist_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}