<?php

/**
 * BasePartner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $logo
 * @property text $body
 * @property string $link
 * @property integer $order_field
 * 
 * @method string  getTitle()       Returns the current record's "title" value
 * @method string  getLogo()        Returns the current record's "logo" value
 * @method text    getBody()        Returns the current record's "body" value
 * @method string  getLink()        Returns the current record's "link" value
 * @method integer getOrderField()  Returns the current record's "order_field" value
 * @method Partner setTitle()       Sets the current record's "title" value
 * @method Partner setLogo()        Sets the current record's "logo" value
 * @method Partner setBody()        Sets the current record's "body" value
 * @method Partner setLink()        Sets the current record's "link" value
 * @method Partner setOrderField()  Sets the current record's "order_field" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePartner extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('partner');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('logo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('body', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('order_field', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}