<?php

/**
 * BaseReceive_datetime
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $reception_id
 * @property timestamp $datetime
 * @property Reception_contract $Reception_contract
 * 
 * @method integer            getReceptionId()        Returns the current record's "reception_id" value
 * @method timestamp          getDatetime()           Returns the current record's "datetime" value
 * @method Reception_contract getReceptionContract()  Returns the current record's "Reception_contract" value
 * @method Receive_datetime   setReceptionId()        Sets the current record's "reception_id" value
 * @method Receive_datetime   setDatetime()           Sets the current record's "datetime" value
 * @method Receive_datetime   setReceptionContract()  Sets the current record's "Reception_contract" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReceive_datetime extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('receive_datetime');
        $this->hasColumn('reception_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('datetime', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Reception_contract', array(
             'local' => 'reception_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}