<?php

/**
 * BaseQuestionSpecialist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $question_id
 * @property integer $specialist_id
 * @property Question $Question
 * @property Specialist $Specialist
 * 
 * @method integer            getQuestionId()    Returns the current record's "question_id" value
 * @method integer            getSpecialistId()  Returns the current record's "specialist_id" value
 * @method Question           getQuestion()      Returns the current record's "Question" value
 * @method Specialist         getSpecialist()    Returns the current record's "Specialist" value
 * @method QuestionSpecialist setQuestionId()    Sets the current record's "question_id" value
 * @method QuestionSpecialist setSpecialistId()  Sets the current record's "specialist_id" value
 * @method QuestionSpecialist setQuestion()      Sets the current record's "Question" value
 * @method QuestionSpecialist setSpecialist()    Sets the current record's "Specialist" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuestionSpecialist extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('question_specialist');
        $this->hasColumn('question_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('specialist_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Question', array(
             'local' => 'question_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Specialist', array(
             'local' => 'specialist_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}