<?php

/**
 * BaseLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $modelname
 * @property string $serialize
 * 
 * @method string getModelname() Returns the current record's "modelname" value
 * @method string getSerialize() Returns the current record's "serialize" value
 * @method Log    setModelname() Sets the current record's "modelname" value
 * @method Log    setSerialize() Sets the current record's "serialize" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('log');
        $this->hasColumn('modelname', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('serialize', 'string', 50000, array(
             'type' => 'string',
             'length' => 50000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}