<?php

/**
 * BaseLogMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $type
 * @property string $body
 * 
 * @method string     getType() Returns the current record's "type" value
 * @method string     getBody() Returns the current record's "body" value
 * @method LogMessage setType() Sets the current record's "type" value
 * @method LogMessage setBody() Sets the current record's "body" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLogMessage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('log_message');
        $this->hasColumn('type', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('body', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}