<?php

/**
 * BaseDocumentation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $file
 * @property integer $order_field
 * 
 * @method string        getTitle()       Returns the current record's "title" value
 * @method string        getFile()        Returns the current record's "file" value
 * @method integer       getOrderField()  Returns the current record's "order_field" value
 * @method Documentation setTitle()       Sets the current record's "title" value
 * @method Documentation setFile()        Sets the current record's "file" value
 * @method Documentation setOrderField()  Sets the current record's "order_field" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDocumentation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('documentation');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('order_field', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}