<?php

/**
 * BaseSheetHistoryField
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sheet_history_id
 * @property string $title
 * @property string $field_type
 * @property string $field_options
 * @property integer $order_field
 * @property boolean $is_required
 * @property SheetHistory $SheetHistory
 * @property Doctrine_Collection $QuestionSheetHistory
 * 
 * @method integer             getSheetHistoryId()       Returns the current record's "sheet_history_id" value
 * @method string              getTitle()                Returns the current record's "title" value
 * @method string              getFieldType()            Returns the current record's "field_type" value
 * @method string              getFieldOptions()         Returns the current record's "field_options" value
 * @method integer             getOrderField()           Returns the current record's "order_field" value
 * @method boolean             getIsRequired()           Returns the current record's "is_required" value
 * @method SheetHistory        getSheetHistory()         Returns the current record's "SheetHistory" value
 * @method Doctrine_Collection getQuestionSheetHistory() Returns the current record's "QuestionSheetHistory" collection
 * @method SheetHistoryField   setSheetHistoryId()       Sets the current record's "sheet_history_id" value
 * @method SheetHistoryField   setTitle()                Sets the current record's "title" value
 * @method SheetHistoryField   setFieldType()            Sets the current record's "field_type" value
 * @method SheetHistoryField   setFieldOptions()         Sets the current record's "field_options" value
 * @method SheetHistoryField   setOrderField()           Sets the current record's "order_field" value
 * @method SheetHistoryField   setIsRequired()           Sets the current record's "is_required" value
 * @method SheetHistoryField   setSheetHistory()         Sets the current record's "SheetHistory" value
 * @method SheetHistoryField   setQuestionSheetHistory() Sets the current record's "QuestionSheetHistory" collection
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSheetHistoryField extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sheet_history_field');
        $this->hasColumn('sheet_history_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 1000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 1000,
             ));
        $this->hasColumn('field_type', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('field_options', 'string', 10000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 10000,
             ));
        $this->hasColumn('order_field', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('is_required', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SheetHistory', array(
             'local' => 'sheet_history_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('QuestionSheetHistory', array(
             'local' => 'id',
             'foreign' => 'sheet_history_field_id'));
    }
}