<?php

/**
 * BaseCertificate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $specialist_id
 * @property string $name
 * @property string $photo
 * @property Specialist $Specialist
 * 
 * @method integer     getSpecialistId()  Returns the current record's "specialist_id" value
 * @method string      getName()          Returns the current record's "name" value
 * @method string      getPhoto()         Returns the current record's "photo" value
 * @method Specialist  getSpecialist()    Returns the current record's "Specialist" value
 * @method Certificate setSpecialistId()  Sets the current record's "specialist_id" value
 * @method Certificate setName()          Sets the current record's "name" value
 * @method Certificate setPhoto()         Sets the current record's "photo" value
 * @method Certificate setSpecialist()    Sets the current record's "Specialist" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCertificate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('certificate');
        $this->hasColumn('specialist_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('photo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Specialist', array(
             'local' => 'specialist_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}