<?php

/**
 * BaseConsilium
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $question_id
 * @property boolean $closed
 * @property timestamp $closing_date
 * @property Question $Question
 * @property Doctrine_Collection $Specialists
 * @property Doctrine_Collection $ConsiliumSpecialist
 * @property Doctrine_Collection $Consilium_answer
 * 
 * @method integer             getQuestionId()          Returns the current record's "question_id" value
 * @method boolean             getClosed()              Returns the current record's "closed" value
 * @method timestamp           getClosingDate()         Returns the current record's "closing_date" value
 * @method Question            getQuestion()            Returns the current record's "Question" value
 * @method Doctrine_Collection getSpecialists()         Returns the current record's "Specialists" collection
 * @method Doctrine_Collection getConsiliumSpecialist() Returns the current record's "ConsiliumSpecialist" collection
 * @method Doctrine_Collection getConsiliumAnswer()     Returns the current record's "Consilium_answer" collection
 * @method Consilium           setQuestionId()          Sets the current record's "question_id" value
 * @method Consilium           setClosed()              Sets the current record's "closed" value
 * @method Consilium           setClosingDate()         Sets the current record's "closing_date" value
 * @method Consilium           setQuestion()            Sets the current record's "Question" value
 * @method Consilium           setSpecialists()         Sets the current record's "Specialists" collection
 * @method Consilium           setConsiliumSpecialist() Sets the current record's "ConsiliumSpecialist" collection
 * @method Consilium           setConsiliumAnswer()     Sets the current record's "Consilium_answer" collection
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConsilium extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('consilium');
        $this->hasColumn('question_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('closed', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('closing_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Question', array(
             'local' => 'question_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Specialist as Specialists', array(
             'refClass' => 'ConsiliumSpecialist',
             'local' => 'consilium_id',
             'foreign' => 'specialist_id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ConsiliumSpecialist', array(
             'local' => 'id',
             'foreign' => 'consilium_id'));

        $this->hasMany('Consilium_answer', array(
             'local' => 'id',
             'foreign' => 'consilium_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}