<?php

/**
 * BaseDeviceTokens
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $token
 * @property integer $type
 * @property User $User
 * 
 * @method integer      getUserId()  Returns the current record's "user_id" value
 * @method string       getToken()   Returns the current record's "token" value
 * @method integer      getType()    Returns the current record's "type" value
 * @method User         getUser()    Returns the current record's "User" value
 * @method DeviceTokens setUserId()  Sets the current record's "user_id" value
 * @method DeviceTokens setToken()   Sets the current record's "token" value
 * @method DeviceTokens setType()    Sets the current record's "type" value
 * @method DeviceTokens setUser()    Sets the current record's "User" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDeviceTokens extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('device_tokens');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('type', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}