<?php

/**
 * BaseComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $article_id
 * @property integer $prompt_id
 * @property text $body
 * @property User $User
 * @property Article $Article
 * @property Prompt $Prompt
 * 
 * @method integer getUserId()     Returns the current record's "user_id" value
 * @method integer getArticleId()  Returns the current record's "article_id" value
 * @method integer getPromptId()   Returns the current record's "prompt_id" value
 * @method text    getBody()       Returns the current record's "body" value
 * @method User    getUser()       Returns the current record's "User" value
 * @method Article getArticle()    Returns the current record's "Article" value
 * @method Prompt  getPrompt()     Returns the current record's "Prompt" value
 * @method Comment setUserId()     Sets the current record's "user_id" value
 * @method Comment setArticleId()  Sets the current record's "article_id" value
 * @method Comment setPromptId()   Sets the current record's "prompt_id" value
 * @method Comment setBody()       Sets the current record's "body" value
 * @method Comment setUser()       Sets the current record's "User" value
 * @method Comment setArticle()    Sets the current record's "Article" value
 * @method Comment setPrompt()     Sets the current record's "Prompt" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('prompt_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('body', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Article', array(
             'local' => 'article_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Prompt', array(
             'local' => 'prompt_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}