<?php

/**
 * BaseDonate_sponsors
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $second_name
 * @property string $middle_name
 * @property integer $amount
 * @property bigint $sender
 * @property boolean $anonymous
 * @property string $json
 * 
 * @method string          getFirstName()   Returns the current record's "first_name" value
 * @method string          getSecondName()  Returns the current record's "second_name" value
 * @method string          getMiddleName()  Returns the current record's "middle_name" value
 * @method integer         getAmount()      Returns the current record's "amount" value
 * @method bigint          getSender()      Returns the current record's "sender" value
 * @method boolean         getAnonymous()   Returns the current record's "anonymous" value
 * @method string          getJson()        Returns the current record's "json" value
 * @method Donate_sponsors setFirstName()   Sets the current record's "first_name" value
 * @method Donate_sponsors setSecondName()  Sets the current record's "second_name" value
 * @method Donate_sponsors setMiddleName()  Sets the current record's "middle_name" value
 * @method Donate_sponsors setAmount()      Sets the current record's "amount" value
 * @method Donate_sponsors setSender()      Sets the current record's "sender" value
 * @method Donate_sponsors setAnonymous()   Sets the current record's "anonymous" value
 * @method Donate_sponsors setJson()        Sets the current record's "json" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDonate_sponsors extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('donate_sponsors');
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('second_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('middle_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('amount', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('sender', 'bigint', 40, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 40,
             ));
        $this->hasColumn('anonymous', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('json', 'string', 10000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}