<?php

/**
 * BaseQuestionSpecialty
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $question_id
 * @property integer $specialty_id
 * @property Question $Question
 * @property Specialty $Specialty
 * 
 * @method integer           getQuestionId()   Returns the current record's "question_id" value
 * @method integer           getSpecialtyId()  Returns the current record's "specialty_id" value
 * @method Question          getQuestion()     Returns the current record's "Question" value
 * @method Specialty         getSpecialty()    Returns the current record's "Specialty" value
 * @method QuestionSpecialty setQuestionId()   Sets the current record's "question_id" value
 * @method QuestionSpecialty setSpecialtyId()  Sets the current record's "specialty_id" value
 * @method QuestionSpecialty setQuestion()     Sets the current record's "Question" value
 * @method QuestionSpecialty setSpecialty()    Sets the current record's "Specialty" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuestionSpecialty extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('question_specialty');
        $this->hasColumn('question_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('specialty_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Question', array(
             'local' => 'question_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Specialty', array(
             'local' => 'specialty_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}