<?php

/**
 * BaseBanner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $link
 * @property string $photo
 * @property boolean $is_activated
 * @property integer $order_field
 * 
 * @method string  getTitle()        Returns the current record's "title" value
 * @method string  getLink()         Returns the current record's "link" value
 * @method string  getPhoto()        Returns the current record's "photo" value
 * @method boolean getIsActivated()  Returns the current record's "is_activated" value
 * @method integer getOrderField()   Returns the current record's "order_field" value
 * @method Banner  setTitle()        Sets the current record's "title" value
 * @method Banner  setLink()         Sets the current record's "link" value
 * @method Banner  setPhoto()        Sets the current record's "photo" value
 * @method Banner  setIsActivated()  Sets the current record's "is_activated" value
 * @method Banner  setOrderField()   Sets the current record's "order_field" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBanner extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('banner');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('photo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('order_field', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}