<?php

/**
 * BaseSpecialist_online
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $specialist_id
 * @property timestamp $date
 * @property Specialist $Specialist
 * 
 * @method integer           getSpecialistId()  Returns the current record's "specialist_id" value
 * @method timestamp         getDate()          Returns the current record's "date" value
 * @method Specialist        getSpecialist()    Returns the current record's "Specialist" value
 * @method Specialist_online setSpecialistId()  Sets the current record's "specialist_id" value
 * @method Specialist_online setDate()          Sets the current record's "date" value
 * @method Specialist_online setSpecialist()    Sets the current record's "Specialist" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSpecialist_online extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('specialist_online');
        $this->hasColumn('specialist_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Specialist', array(
             'local' => 'specialist_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}