<?php

/**
 * Agreement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Agreement extends BaseAgreement
{
  static function agreementCheck($user_id)
  {
    $agreement_check = Doctrine_Query::create()
      ->select("COUNT(*) AS count")
      ->from("agreement a")
      ->addSelect("(SELECT COUNT(*) FROM AgreementComplete ac WHERE ac.user_id = " . $user_id . ") AS user_count")
      ->fetchArray()
    ;
    $result = false;
    if($agreement_check[0]['count'] > $agreement_check[0]['user_count'])
    {
      $result = true;
    }
    return $result;
  }
}
