<?php

/**
 * Answer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Answer extends BaseAnswer
{
  public static function AnswerType($type, $view = false)
  {
    $valid_type = array(
      '',
      'user_reception' => 'Пациент хочет записаться на приём',
      'please_analysis' => 'Отправлена анкета для анализов',
      'please_analysis_complete' => 'Отправлена анкета для анализов',
      'give_analysis' => 'Анализы прикреплены',
      'email_reminder' => 'Отправлено напоминание на электронную почту'
    );
    $result = $valid_type[$type] ? $valid_type[$type] : false;
    if($view == 'list')
    {
      $result = $valid_type;
    }
    return $result;
  }
  public static function AnswerNew($param)
  {
    $user_answer = new Answer();
    $user_answer->setUserId($param['user_id']);
    $user_answer->setQuestionId($param['question_id']);
    $user_answer->setBody($param['body']);
    $user_answer->setCommentId($param['mid']);
    if($param['date'])
    {
      $user_answer->setCreatedAt(date('Y-m-d' . ' ' . 'H:i:s', $param['date']));
    }
    $user_answer->save();
  }
  public function save(Doctrine_Connection $conn = null)
  {
    $specialist = $this->getUser()->getSpecialist();
    $question = $this->getQuestion();
    if(count($specialist) > 0 && $question->getApproved() != 1)
    {
      if($question->getUserId() != 7184)
      {
        $question->setApproved(1);
        $question->save();
      }
    }
    if($question->getCommentId() != '' && $question->getUserId() != $this->getUserId())
    {
      $vk_message_type = $question->getTopicId() ? 'topic' : false;
      if(!Answer::AnswerType($this->getType(), false) || $this->getType() == 'please_analysis')
      {        
        if(sfConfig::get('app_vk_publish') && !$this->getCommentId() && $this->isNew() && ($question->getVkNotice() == 0 || !$question->getVkNotice()))        
        {
          $comment_id = Question::syncToVk($this, $vk_message_type);
          if($comment_id)
          {
            $question->setVkNotice(1);
            $question->save();

            $this->setCommentId($comment_id);
          }
        }
      }
    }
    $specialist = Doctrine::getTable("Specialist")->findOneByUserId($this->getUserId());
    $result = parent::save($conn);

    if(sfConfig::get('app_vk_publish') || is_null($this->getCommentId()))
    {
      $notice_type = $this->getType() == '' ? 'message' : $this->getType();
      Page::noticeAdd((!$specialist ? 's' : 'u'), 'dialog', $this->getQuestionId(), $notice_type, false, $specialist ? $question->getUserId() : '');
    }
    return $result;
  }
}
