<?php

/**
 * Log
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Log extends BaseLog
{
  public function save(Doctrine_Connection $conn = null)
  {
    if($_SERVER['PHP_SELF'] != './symfony')
    {
      
    }
    return parent::save($conn);
  }
  public function delete(Doctrine_Connection $conn = null)
  {
    if($_SERVER['PHP_SELF'] != './symfony')
    {
      
    }
    return parent::delete($conn);
  }
}
