<?php

/**
 * Permission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Permission extends BasePermission
{
  public static function getBasePermission()
  {
    return array(
      'index|filter|search' => 'Просмотр списка',
      'show|edit' => 'Просмотр элемента',
      'new|create' => 'Добавление',
      'update' => 'Редактирование',
      'delete|batchDelete' => 'Удаление',
      'batch|batchMerge' => 'Объединение',
    );
  }
}
