<?php

/**
 * SheetHistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */

class SheetHistory extends BaseSheetHistory
{
  public static function getTypes()
  {
    return array(
      'input' => 'Однострочное поле ввода',
      'textarea' => 'Многострочное поле ввода',
      'textarea_upload' => 'Многострочное поле ввода с загрузкой',
      'yes_no_input' => 'Нет/Да с однострочным полем ввода',
      'yes_no_textarea' => 'Нет/Да с многострочным полем ввода',
      'choices' => 'Список',
    );
  }
  public function getSheetHistoryField()
  {
    return Doctrine::getTable("SheetHistoryField")->createQuery("q")->where("sheet_history_id = " . $this->getId())->orderBy("order_field")->execute();
  }
}
