<?php

/**
 * Specialist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Specialist extends BaseSpecialist
{
  public function getSFM()
  {
    return $this->getUser()->getSFM();
  }
  public function save(Doctrine_Connection $conn = null)
  {
    $this->setTitleUrl(Page::translitUrl($this->getSFM()));
    return parent::save($conn);
  }
}
