generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Documentation
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          documentation
    with_doctrine_route:   true
    actions_base_class:    sfActions
    order: 100
    hr: true

    config:
      actions: ~
      fields:
        id: {label: '№'}
        title: {label: Название}
        file: {label: 'Файл документа'}
        document: {label: 'Файл документа'}
        order_field: {label: 'Порядок сортировки'}
      list:
        layout: ~
        title: 'Документация'
        display: [title, _document, order_field]
        max_per_page: 100
        object_actions:
          _delete: ~
          _edit: ~
        search:
          fields: [title]
        export: false
      filter:
        class: false
      form: ~
      edit:
        title: Редактирование документа
      new:
        title: Добавление документа