all:
  doctrine:
    class: sfDoctrineDatabase
    profiler: false
    param:
      dsn: '<?php echo getenv('DB_DSN') ? getenv('DB_DSN') : 'mysql:host=mysql;dbname=vrachrb.ru';?>'
      username: '<?php echo getenv('DB_USERNAME') ? getenv('DB_USERNAME') : 'root';?>'
      password: '<?php echo getenv('DB_PASSWORD') ? getenv('DB_PASSWORD') : '';?>'
