<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('user_group_permissions', 'user_group_permissions_user_group_id_user_group_id', array(
             'name' => 'user_group_permissions_user_group_id_user_group_id',
             'local' => 'user_group_id',
             'foreign' => 'id',
             'foreignTable' => 'user_group',
             ));
        $this->createForeignKey('user_group_users', 'user_group_users_user_group_id_user_group_id', array(
             'name' => 'user_group_users_user_group_id_user_group_id',
             'local' => 'user_group_id',
             'foreign' => 'id',
             'foreignTable' => 'user_group',
             ));
        $this->createForeignKey('user_permissions', 'user_permissions_user_id_user_id', array(
             'name' => 'user_permissions_user_id_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->addIndex('user_group_permissions', 'user_group_permissions_user_group_id', array(
             'fields' => 
             array(
              0 => 'user_group_id',
             ),
             ));
        $this->addIndex('user_group_users', 'user_group_users_user_group_id', array(
             'fields' => 
             array(
              0 => 'user_group_id',
             ),
             ));
        $this->addIndex('user_permissions', 'user_permissions_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('user_group_permissions', 'user_group_permissions_user_group_id_user_group_id');
        $this->dropForeignKey('user_group_users', 'user_group_users_user_group_id_user_group_id');
        $this->dropForeignKey('user_permissions', 'user_permissions_user_id_user_id');
        $this->removeIndex('user_group_permissions', 'user_group_permissions_user_group_id', array(
             'fields' => 
             array(
              0 => 'user_group_id',
             ),
             ));
        $this->removeIndex('user_group_users', 'user_group_users_user_group_id', array(
             'fields' => 
             array(
              0 => 'user_group_id',
             ),
             ));
        $this->removeIndex('user_permissions', 'user_permissions_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }
}