generator:
  class: sfDoctrineGenerator
  param:
    model_class:           News
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          news
    with_doctrine_route:   true
    actions_base_class:    sfActions
    order: 30

    config:
      actions: ~
      fields:
        id: {label: '№'}
        title: {label: Название}
        body: {label: 'Текст новости'}
        photo: {label: 'Фотография'}
        video: {label: 'Код видео www.youtube.com'}
        created_at: {label: 'Дата создания'}
        updated_at: {label: 'Дата изменения'}
      list:
        layout: ~
        title: 'Новости'
        display: [title, _photo, created_at]
        sort: [created_at, desc]
        max_per_page: 100
        object_actions:
          _delete: ~
          _edit: ~
        search:
          fields: [title]
        export: false
      filter:
        class: false
      form: ~
      edit:
        title: Редактирование новости
      new:
        title: Добавление новости