prod:
  .settings:
    logging_enabled: false
    cache: false

dev:
  .settings:
#    error_reporting: <?php echo (E_ALL | E_STRICT)."\n" ?>
#    error_reporting: <?php echo (E_ALL ^ E_STRICT ^ E_NOTICE ^ E_DEPRECATED ^ E_USER_DEPRECATED)."\n" ?>
    error_reporting: <?php echo ((E_ALL) ^ E_NOTICE)."\n" ?>
    web_debug: false
    cache: false
    etag: false
    logging_enabled: false

all:
  .settings:
    csrf_secret: 2450ecb2853511b9f9137ee54890608d0b8c62dd
    escaping_strategy: true
    escaping_method: ESC_SPECIALCHARS
    use_database: true
    no_script_name: true
    enabled_modules: [default, sfCaptchaGD, csSetting]
    default_culture: ru_RU
    standard_helpers: [Partial, Cache, I18N]
    i18n: true
  .actions:
    error_404_module: main
    error_404_action: error404
    login_module: user
    login_action: login
    secure_module: user
    secure_action: secure