generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Notice
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          notice
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        id: {label: '№'}
        user_id: {label: 'Пользователь'}
        user: {label: 'Пользователь'}
        type: {label: 'Раздел'}
        inner_id: {label: 'Элемент'}
        event: {label: 'Событие'}
        notice_event: {label: 'Событие'}
        created_at: {label: 'Дата создания'}
        updated_at: {label: 'Дата изменения'}
      list:
        layout: ~
        title: 'Уведомления'
        display: [_user, type, inner_id, _notice_event]
        max_per_page: 100
        object_actions:
          _delete: ~
          _edit: ~
        search:
          fields: [u.first_name, u.second_name, u.middle_name]
        export: false
      filter:
        class: false
      form: ~
      edit:
        title: Редактирование 
      new:
        title: Добавление 